services:
  # PostgreSQL database
  postgres1:
    image: postgres:latest
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflowdb
#    ports:
#      - 5432:5432
    volumes:
      - ./postgres-data1:/var/lib/postgresql/data
    networks:
      - serving_network
  postgres2:
    image: postgres:latest
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow_user
#    ports:
#      - 5433:5432
    volumes:
      - ./postgres-data2:/var/lib/postgresql/data
    networks:
      - serving_network
  # MLflow Server
  mlflow:
    image: mlflow/mlflow_service
    build: ./mlflow
    ports:
      - 8668:8668
    container_name: mlflow_service
    networks:
      - serving_network
  # Serving Server
  serving:
    image: serving/serving_service
    build: ./app
    ports:
      - 8829:8829
    container_name: serving_service
    networks:
      - serving_network
networks:
  serving_network:
    driver: bridge
